name: Build Library

on:
  pull_request:
    branches: [ master ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: wagoid/commitlint-github-action@v2

    - name: Add dotnet-format problem matcher
      uses: xt0rted/dotnet-format-problem-matcher@v1

    - name: Restore dotnet tools
      uses: xt0rted/dotnet-tool-restore@v1

    - name: Run dotnet format
      uses: xt0rted/dotnet-format@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        only-changed-files: "true"

  build:
    name: Build (dotnet ${{ matrix.version }})
    strategy:
      matrix:
        version: [2.1.811, 3.1.403]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core (dotnet ${{ matrix.version }})
      uses: actions/setup-dotnet@v1
      with:
          dotnet-version: ${{ matrix.version }}
    - name: Install dependencies (dotnet ${{ matrix.version }})
      run: dotnet restore
    - name: Build (dotnet ${{ matrix.version }})
      run: dotnet build --configuration Release --no-restore
